export const SKILLS = [
  'Frontend Development',
  'Backend Development',
  'UI/UX Design',
  'Product Management',
  'Marketing',
  'Business Development',
  'Data Science',
  'Machine Learning',
  'Blockchain Development',
  'Smart Contracts',
  'DevOps',
  'Mobile Development',
  'Content Creation',
  'Community Management',
  'Sales',
  'Finance',
  'Legal',
  'Operations',
];

export const VALUES = [
  'Open Source',
  'Sustainability',
  'Privacy',
  'Decentralization',
  'Innovation',
  'Transparency',
  'Accessibility',
  'Diversity & Inclusion',
  'Education',
  'Social Impact',
  'AI Ethics',
  'Remote Work',
  'Work-Life Balance',
  'Continuous Learning',
];

export const COLLABORATION_GOALS = [
  'Build an AI Art Generator',
  'Launch a Podcast',
  'Develop a DeFi Protocol',
  'Create a Mobile App',
  'Start a Newsletter',
  'Build a SaaS Product',
  'Launch an NFT Collection',
  'Create Educational Content',
  'Develop a Game',
  'Build a Community Platform',
  'Start a Consulting Business',
  'Create a Marketplace',
  'Develop IoT Solutions',
  'Build Analytics Tools',
  'Launch a DAO',
];

export const PROJECT_TEMPLATES = [
  {
    id: 'saas-startup',
    name: 'SaaS Startup',
    description: 'Template for launching a software-as-a-service business',
    roles: ['Technical Lead', 'Product Manager', 'Marketing Lead'],
    milestones: [
      'Market Research & Validation',
      'MVP Development',
      'Beta Testing',
      'Launch & Marketing',
      'Growth & Scaling',
    ],
  },
  {
    id: 'content-creation',
    name: 'Content Creation',
    description: 'Template for collaborative content projects',
    roles: ['Content Creator', 'Editor', 'Designer', 'Marketer'],
    milestones: [
      'Content Strategy',
      'Content Production',
      'Review & Editing',
      'Publishing & Promotion',
      'Performance Analysis',
    ],
  },
  {
    id: 'blockchain-project',
    name: 'Blockchain Project',
    description: 'Template for decentralized application development',
    roles: ['Smart Contract Developer', 'Frontend Developer', 'Community Manager'],
    milestones: [
      'Protocol Design',
      'Smart Contract Development',
      'Frontend Development',
      'Testing & Audit',
      'Mainnet Launch',
    ],
  },
];
